--  Backup Tables for Safety
CREATE TABLE BKPTREARN20251213 AS SELECT * FROM PTREARN;-- Base earning record
CREATE TABLE BKPTRECLD20251213 AS SELECT * FROM PTRECLD;-- PTREARN Earnings Code Labor Distribution Override tab
CREATE TABLE BKPTREERN20251213 AS SELECT * FROM PTREERN;-- PTRECLS Eligible Earnings tab
CREATE TABLE BKPTRBDXE20251213 AS SELECT * FROM PTRBDXE;-- PTRBDCA Excluded Earnings tab
CREATE TABLE BKPXRRERN20251213 AS SELECT * FROM PXRRERN;-- Tax Reporting Rules (PXAREPT)

DECLARE
  P_OLD_EARN_CODE PTREARN.PTREARN_CODE%TYPE := :OLD_EARN_CODE;
  P_NEW_EARN_CODE PTREARN.PTREARN_CODE%TYPE := :NEW_EARN_CODE; -- optional, if null will use old code and assume a copy from a test instance
  P_NEW_SHORT_DESC PTREARN.PTREARN_SHORT_DESC%TYPE := :NEW_SHORT_DESC; -- optional
  P_NEW_LONG_DESC PTREARN.PTREARN_LONG_DESC%TYPE := :NEW_LONG_DESC; -- optional
  LV_DATA_ORIGIN PTREARN.PTREARN_DATA_ORIGIN%TYPE := NULL;
  LV_REC_CNT NUMBER := 0;

/* ***************************************************************
    Revisions
    DATE        Programmer          Revision Notes
    2025-12-13  Steven Clark        Original Anonymous Block

    NOTES:  May need to add someday:  PTRECER, PTRLVPR, PTRPERN, PTRPPAS, PTRSEHS, PTRSERN, Others?

            IMPORTANT:  be sure the database link (@ZPPRD) is where you want it, and that you''re logged into
                        the instance to which you are copying.

    Example Code to Run:
        BEGIN
            Z_ZHRBDCA_COPY (P_NEW_BDCA => '522', P_OLD_BDCA => '522', P_EFF_DATE => TO_DATE('01-DEC-2022','DD-MON-YYYY'));
            Z_ZHRBDCA_COPY (P_NEW_BDCA => '526', P_OLD_BDCA => '526', P_EFF_DATE => TO_DATE('01-DEC-2022','DD-MON-YYYY'));
        END;
        
    
        -- VIEW PTRBDCA SETUP
        select * from ptrbdca where ptrbdca_code in ('522','526');
*/

BEGIN
  -- Header Record
  DBMS_OUTPUT.PUT_LINE('NEW' || CHR(9) || 'OLD' || CHR(9) || 'TABLE' || CHR(9) || 'EXISTING' || CHR(9) || 'ROWCOUNT' || CHR(9) || 'ACTION' || CHR(9) || 'TABLE_DESC');

  P_NEW_EARN_CODE := COALESCE(P_NEW_EARN_CODE,P_OLD_EARN_CODE);

  IF P_NEW_EARN_CODE = P_OLD_EARN_CODE THEN
    LV_DATA_ORIGIN := 'COPY FROM TEST INSTANCE SETUP';
  ELSE
    LV_DATA_ORIGIN := 'COPY FROM ' || P_OLD_EARN_CODE;
  END IF;

  -- PTREARN - Base earning record
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTREARN WHERE PTREARN_CODE = P_NEW_EARN_CODE;
  INSERT INTO PTREARN 
    (   PTREARN_CODE
      , PTREARN_SHORT_DESC
      , PTREARN_LONG_DESC
      , PTREARN_RATE_IND
      , PTREARN_RATE
      , PTREARN_MULT_FACTOR
      , PTREARN_TYPE_IND
      , PTREARN_CASH_IND
      , PTREARN_SHFT_DIFF_IND
      , PTREARN_TAX_METHOD_IND
      , PTREARN_LEAV_CODE_TAKEN
      , PTREARN_LEAV_CODE_EARNED
      , PTREARN_LEAV_PRORATION_IND
      , PTREARN_LEAV_MINIMUM_IND
      , PTREARN_ECLD_IND
      , PTREARN_BASE_SAL_IND
      , PTREARN_EXCEPTION_IND
      , PTREARN_EXPENDED_BUD_IND
      , PTREARN_UNIT_IND
      , PTREARN_LONGEVITY_IND
      , PTREARN_FLSA_HRS_IND
      , PTREARN_FLSA_AMT_IND
      , PTREARN_RUCL_CODE
      , PTREARN_1099_CODE
      , PTREARN_PENSIONABLE_HRS_IND
      , PTREARN_FRINGE_IND
      , PTREARN_ACTIVITY_DATE
      , PTREARN_STIPEND_IND
      , PTREARN_ERGR_CODE
      , PTREARN_SPECIAL_COMP_IND
      , PTREARN_WEB_DISP_IND
      , PTREARN_NOT_DETERMINED_IND
      , PTREARN_OSHA_HRS_IND
      , PTREARN_MIS_ADDL_EARN_IND
      , PTREARN_RUCL_CODE_FRNG
      , PTREARN_FMLA_ELIGIBLE_HRS_IND
      , PTREARN_FMLA_USAGE_HRS_IND
      , PTREARN_USER_ID
      , PTREARN_DATA_ORIGIN
      , PTREARN_DISP_WEB_PAYSTUB_IND
      , PTREARN_MIS_EB13_EARN_IND
      , PTREARN_PRIOR_PERIOD_IND
      , PTREARN_PSCT_CODE
      , PTREARN_CSET_CODE
    )
  SELECT 
      P_NEW_EARN_CODE PTREARN_CODE
    , COALESCE(P_NEW_SHORT_DESC,PTREARN_SHORT_DESC) PTREARN_SHORT_DESC
    , COALESCE(P_NEW_LONG_DESC,PTREARN_LONG_DESC) PTREARN_LONG_DESC
    , PTREARN_RATE_IND
    , PTREARN_RATE
    , PTREARN_MULT_FACTOR
    , PTREARN_TYPE_IND
    , PTREARN_CASH_IND
    , PTREARN_SHFT_DIFF_IND
    , PTREARN_TAX_METHOD_IND
    , PTREARN_LEAV_CODE_TAKEN
    , PTREARN_LEAV_CODE_EARNED
    , PTREARN_LEAV_PRORATION_IND
    , PTREARN_LEAV_MINIMUM_IND
    , PTREARN_ECLD_IND
    , PTREARN_BASE_SAL_IND
    , PTREARN_EXCEPTION_IND
    , PTREARN_EXPENDED_BUD_IND
    , PTREARN_UNIT_IND
    , PTREARN_LONGEVITY_IND
    , PTREARN_FLSA_HRS_IND
    , PTREARN_FLSA_AMT_IND
    , PTREARN_RUCL_CODE
    , PTREARN_1099_CODE
    , PTREARN_PENSIONABLE_HRS_IND
    , PTREARN_FRINGE_IND
    , SYSDATE PTREARN_ACTIVITY_DATE
    , PTREARN_STIPEND_IND
    , PTREARN_ERGR_CODE
    , PTREARN_SPECIAL_COMP_IND
    , PTREARN_WEB_DISP_IND
    , PTREARN_NOT_DETERMINED_IND
    , PTREARN_OSHA_HRS_IND
    , PTREARN_MIS_ADDL_EARN_IND
    , PTREARN_RUCL_CODE_FRNG
    , PTREARN_FMLA_ELIGIBLE_HRS_IND
    , PTREARN_FMLA_USAGE_HRS_IND
    , USER PTREARN_USER_ID
    , LV_DATA_ORIGIN PTREARN_DATA_ORIGIN
    , PTREARN_DISP_WEB_PAYSTUB_IND
    , PTREARN_MIS_EB13_EARN_IND
    , PTREARN_PRIOR_PERIOD_IND
    , PTREARN_PSCT_CODE
    , PTREARN_CSET_CODE
  FROM PTREARN@ZPPRD
  WHERE PTREARN_CODE = P_OLD_EARN_CODE
    AND NOT EXISTS ( SELECT PTREARN_CODE FROM PTREARN WHERE PTREARN_CODE = P_NEW_EARN_CODE )
  ;

  DBMS_OUTPUT.PUT_LINE(P_NEW_EARN_CODE || CHR(9) || P_OLD_EARN_CODE || CHR(9) || 'PTREARN' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'BASE EARNING RECORD');

  -- PTRECLD - Earnings Code Labor Distribution Override tab
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRECLD WHERE PTRECLD_CODE = P_NEW_EARN_CODE;
  INSERT INTO PTRECLD 
    ( PTRECLD_CODE
    , PTRECLD_ECLS_CODE
    , PTRECLD_COAS_CODE
    , PTRECLD_ACCI_CODE
    , PTRECLD_FUND_CODE
    , PTRECLD_ORGN_CODE
    , PTRECLD_ACCT_CODE
    , PTRECLD_PROG_CODE
    , PTRECLD_ACTV_CODE
    , PTRECLD_LOCN_CODE
    , PTRECLD_ACCT_CODE_EXTERNAL
    , PTRECLD_ACTIVITY_DATE
    , PTRECLD_PROJ_CODE
    , PTRECLD_CTYP_CODE
    , PTRECLD_USER_ID
    , PTRECLD_DATA_ORIGIN
    )
  SELECT 
      P_NEW_EARN_CODE PTRECLD_CODE
    , PTRECLD_ECLS_CODE
    , PTRECLD_COAS_CODE
    , PTRECLD_ACCI_CODE
    , PTRECLD_FUND_CODE
    , PTRECLD_ORGN_CODE
    , PTRECLD_ACCT_CODE
    , PTRECLD_PROG_CODE
    , PTRECLD_ACTV_CODE
    , PTRECLD_LOCN_CODE
    , PTRECLD_ACCT_CODE_EXTERNAL
    , SYSDATE PTRECLD_ACTIVITY_DATE
    , PTRECLD_PROJ_CODE
    , PTRECLD_CTYP_CODE
    , USER PTRECLD_USER_ID
    , LV_DATA_ORIGIN PTRECLD_DATA_ORIGIN
  FROM PTRECLD@ZPPRD 
  WHERE PTRECLD_CODE = P_OLD_EARN_CODE
    AND NOT EXISTS ( SELECT 1 FROM PTRECLD JR WHERE JR.PTRECLD_CODE = P_NEW_EARN_CODE AND JR.PTRECLD_ECLS_CODE = PTRECLD.PTRECLD_ECLS_CODE )
  ; 

  DBMS_OUTPUT.PUT_LINE(P_NEW_EARN_CODE || CHR(9) || P_OLD_EARN_CODE || CHR(9) || 'PTRECLD' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'LABOR DISTRIBUTION OVERRIDE');

  -- PTREERN - Eligible Earnings tab
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTREERN WHERE PTREERN_EARN_CODE = P_NEW_EARN_CODE;
  INSERT INTO PTREERN 
    ( PTREERN_ECLS_CODE
    , PTREERN_EARN_CODE
    , PTREERN_ATND_IND
    , PTREERN_REDUCE_REG_PAY_IND
    , PTREERN_TS_ENTRY_SEQ
    , PTREERN_TS_PRINT_SEQ
    , PTREERN_ACTIVITY_DATE
    , PTREERN_EA_APPROVERS_IND
    , PTREERN_ACCRUE_SENIORITY_IND
    , PTREERN_CLOCK_IN_OUT_IND
    , PTREERN_USER_ID
    , PTREERN_DATA_ORIGIN
    )
  SELECT
      PTREERN_ECLS_CODE
    , P_NEW_EARN_CODE PTREERN_EARN_CODE
    , PTREERN_ATND_IND
    , PTREERN_REDUCE_REG_PAY_IND
    , NULL PTREERN_TS_ENTRY_SEQ
    , NULL PTREERN_TS_PRINT_SEQ
    , SYSDATE PTREERN_ACTIVITY_DATE
    , PTREERN_EA_APPROVERS_IND
    , PTREERN_ACCRUE_SENIORITY_IND
    , PTREERN_CLOCK_IN_OUT_IND
    , USER PTREERN_USER_ID
    , LV_DATA_ORIGIN PTREERN_DATA_ORIGIN
  FROM PTREERN@ZPPRD 
  WHERE PTREERN_EARN_CODE = P_OLD_EARN_CODE
    AND NOT EXISTS ( SELECT 1 FROM PTREERN JR WHERE JR.PTREERN_EARN_CODE = P_NEW_EARN_CODE AND JR.PTREERN_ECLS_CODE = PTREERN.PTREERN_ECLS_CODE )
  ;

  DBMS_OUTPUT.PUT_LINE(P_NEW_EARN_CODE || CHR(9) || P_OLD_EARN_CODE || CHR(9) || 'PTREERN' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'ELIGIBLE EARNINGS');

  -- PTRBDXE - Excluded Earnings tab
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDXE WHERE PTRBDXE_EARN_CODE = P_NEW_EARN_CODE;
  INSERT INTO PTRBDXE 
    ( PTRBDXE_CODE
    , PTRBDXE_EARN_CODE
    , PTRBDXE_ACTIVITY_DATE
    , PTRBDXE_USER_ID
    , PTRBDXE_DATA_ORIGIN
    )
  SELECT
      PTRBDXE_CODE
    , P_NEW_EARN_CODE PTRBDXE_EARN_CODE
    , SYSDATE PTRBDXE_ACTIVITY_DATE
    , USER PTRBDXE_USER_ID
    , LV_DATA_ORIGIN PTRBDXE_DATA_ORIGIN
  FROM PTRBDXE@ZPPRD 
  WHERE PTRBDXE_EARN_CODE = P_OLD_EARN_CODE
    AND NOT EXISTS ( SELECT 1 FROM PTRBDXE JR WHERE JR.PTRBDXE_EARN_CODE = P_NEW_EARN_CODE AND JR.PTRBDXE_CODE = PTRBDXE.PTRBDXE_CODE )
  ;

  DBMS_OUTPUT.PUT_LINE(P_NEW_EARN_CODE || CHR(9) || P_OLD_EARN_CODE || CHR(9) || 'PTRBDXE' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'EXCLUDED EARNINGS');

  -- PXRRERN - Tax Reporting Rules (PXAREPT)
  SELECT COUNT(*) INTO LV_REC_CNT FROM PXRRERN WHERE PXRRERN_EARN_CODE = P_NEW_EARN_CODE;
  INSERT INTO PXRRERN 
    ( PXRRERN_REPT_CODE
    , PXRRERN_RBOX_CODE
    , PXRRERN_EARN_CODE
    , PXRRERN_ACTIVITY_DATE
    , PXRRERN_USER_ID
    , PXRRERN_DATA_ORIGIN
    )
  SELECT
      PXRRERN_REPT_CODE
    , PXRRERN_RBOX_CODE
    , P_NEW_EARN_CODE PXRRERN_EARN_CODE
    , SYSDATE PXRRERN_ACTIVITY_DATE
    , USER PXRRERN_USER_ID
    , LV_DATA_ORIGIN PXRRERN_DATA_ORIGIN
  FROM PXRRERN@ZPPRD 
  WHERE PXRRERN_EARN_CODE = P_OLD_EARN_CODE
    AND NOT EXISTS ( SELECT 1 FROM PXRRERN JR WHERE JR.PXRRERN_EARN_CODE = P_NEW_EARN_CODE AND JR.PXRRERN_REPT_CODE = PXRRERN.PXRRERN_REPT_CODE AND JR.PXRRERN_RBOX_CODE = PXRRERN.PXRRERN_RBOX_CODE )
  ;

  DBMS_OUTPUT.PUT_LINE(P_NEW_EARN_CODE || CHR(9) || P_OLD_EARN_CODE || CHR(9) || 'PXRRERN' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'TAX REPORTING RULES');

END;
/

-- VIEW RESULTS
SELECT * FROM PTREARN WHERE PTREARN_CODE = UPPER(:NEW_EARN_CODE);
SELECT * FROM PTRECLD WHERE PTRECLD_CODE = UPPER(:NEW_EARN_CODE);
SELECT * FROM PTREERN WHERE PTREERN_EARN_CODE = UPPER(:NEW_EARN_CODE);
SELECT * FROM PTRBDXE WHERE PTRBDXE_EARN_CODE = UPPER(:NEW_EARN_CODE);
SELECT * FROM PXRRERN WHERE PXRRERN_EARN_CODE = UPPER(:NEW_EARN_CODE);

-- ROLLBACK;
-- COMMIT;

/* ADDITIONAL CODE */

-- IDENTIFY TABLES WITH EARN CODE COLUMNS
SELECT OWNER, TABLE_NAME, COLUMN_NAME 
FROM DBA_TAB_COLUMNS 
WHERE COLUMN_NAME LIKE UPPER('PTR%EARN_CODE') 
ORDER BY OWNER, TABLE_NAME;

-- TABLES I DID NOT INCLUDE IN COPY
SELECT * FROM PTRECER;
SELECT * FROM PTRLVPR; -- Has VAL earn code twice  (Leave cascading?)
SELECT * FROM PTRPERN;
SELECT * FROM PTRPPAS;
SELECT * FROM PTRSEHS;
SELECT * FROM PTRSERN; -- Has SPY earn code 18 times (Supplemental Earnings?)

--  Earning Code Tables - VIEW BEFORE COPY
SELECT * FROM PTREARN; -- Base earning record
SELECT * FROM PTRECLD; -- PTREARN Earnings Code Labor Distribution Override tab
SELECT * FROM PTREERN; -- PTRECLS Eligible Earnings tab
SELECT * FROM PTRBDXE; -- PTRBDCA Excluded Earnings tab
SELECT * FROM PXRRERN; -- Tax Reporting Rules (PXAREPT) 

--  Earning Code Tables - FILTER BY CODE
SELECT * FROM PTREARN WHERE PTREARN_CODE = :OLD_EARN_CODE; -- Base earning record
SELECT * FROM PTRECLD WHERE PTRECLD_CODE = :OLD_EARN_CODE; -- PTREARN Earnings Code Labor Distribution Override tab
SELECT * FROM PTREERN WHERE PTREERN_EARN_CODE = :OLD_EARN_CODE; -- PTRECLS Eligible Earnings tab
SELECT * FROM PTRBDXE WHERE PTRBDXE_EARN_CODE = :OLD_EARN_CODE; -- PTRBDCA Excluded Earnings tab
SELECT * FROM PXRRERN WHERE PXRRERN_EARN_CODE = :OLD_EARN_CODE; -- Tax Reporting Rules (PXAREPT)
