-- BACKUP TABLES BEFORE RUNNING SCRIPT
CREATE TABLE BKPTRBDCA20251213 AS SELECT * FROM PTRBDCA;
CREATE TABLE BKPTRBDPL20251213 AS SELECT * FROM PTRBDPL;
CREATE TABLE BKPTRBDPD20251213 AS SELECT * FROM PTRBDPD;
CREATE TABLE BKPTRBDAS20251213 AS SELECT * FROM PTRBDAS;
CREATE TABLE BKPTRBDLG20251213 AS SELECT * FROM PTRBDLG;
CREATE TABLE BKPTRBDCG20251213 AS SELECT * FROM PTRBDCG;
CREATE TABLE BKPTRBDID20251213 AS SELECT * FROM PTRBDID;
CREATE TABLE BKPTRBDXD20251213 AS SELECT * FROM PTRBDXD;
CREATE TABLE BKPTRBDXE20251213 AS SELECT * FROM PTRBDXE;
CREATE TABLE BKPTRBDLD20251213 AS SELECT * FROM PTRBDLD;
CREATE TABLE BKPTRBPRV20251213 AS SELECT * FROM PTRBPRV;
CREATE TABLE BKPTRBCDN20251213 AS SELECT * FROM PTRBCDN;
CREATE TABLE BKZHBBDCA20251213 AS SELECT * FROM ZHBBDCA;

DECLARE
  P_OLD_BDCA PTRBDCA.PTRBDCA_CODE%TYPE := :OLD_BDCA_CODE;
  P_NEW_BDCA PTRBDCA.PTRBDCA_CODE%TYPE := :NEW_BDCA_CODE; -- optional, if null will use old code and assume a copy from a test instance
  P_NEW_SHORT_DESC PTRBDCA.PTRBDCA_SHORT_DESC%TYPE := :NEW_SHORT_DESC; -- optional
  P_NEW_LONG_DESC PTRBDCA.PTRBDCA_LONG_DESC%TYPE := :NEW_LONG_DESC; -- optional
  P_BEG_DATE DATE := TO_DATE(:BEGIN_DATE_YYYYMMDD,'YYYYMMDD');
  LV_DATA_ORIGIN PTRBDCA.PTRBDCA_DATA_ORIGIN%TYPE := NULL;
  LV_REC_CNT NUMBER := 0;

/* ***************************************************************
    Revisions
    DATE        Programmer          Revision Notes
    2022-12-21  Steven Clark        Original Package - Built from code by Lisa Molmen (2010) 
                                    - updated for current table structure and converted to a procedure
                                    - added additional tables (including one custom to USU)
                                    - added dbms_output lines for logging
                                    - added checks to avoid duplicate inserts

    NOTES:  
            IMPORTANT:  be sure the database link (@ZPPRD) is where you want it, and that you''re logged into
                        the instance to which you are copying.
            
            May need to add someday:  ptrbsdd (benefit statement display dates, not currently used) 
            and will need to add for life insurance: ptrbdfq (payroll frequency rules)
            For life insurance would need ptrprem, ptrlife, ptrlifi, etc...

            copy_bdca.sql
            May 2010
            Lisa Molmen
            Script to copy all data on a new benefit OR deduction code from a test instance to production.
            Note:  skipping Combined Limits data for right now as it is completely unfamiliar (and unused).
            Note2:  Need to be sure and copy over all pieces of a chained deduction, then chain them in PTRDCHN.
            
*/

BEGIN
  -- Header Record
  DBMS_OUTPUT.PUT_LINE('NEW' || CHR(9) || 'OLD' || CHR(9) || 'TABLE' || CHR(9) || 'EXISTING' || CHR(9) || 'ROWCOUNT' || CHR(9) || 'ACTION' || CHR(9) || 'FOR' || CHR(9) || 'TABLE_DESC');

  P_NEW_BDCA := COALESCE(P_NEW_BDCA,P_OLD_BDCA);

  IF P_NEW_BDCA = P_OLD_BDCA THEN
    LV_DATA_ORIGIN := 'COPY FROM TEST INSTANCE SETUP';
  ELSE
    LV_DATA_ORIGIN := 'COPY FROM ' || P_OLD_BDCA;
  END IF;
  
  -- PTRBDCA - Basic Benefit Rules, Form PTRBDCA:
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDCA WHERE PTRBDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDCA (PTRBDCA_CODE,
    PTRBDCA_SHORT_DESC,
    PTRBDCA_LONG_DESC,
    PTRBDCA_PRIORITY,
    PTRBDCA_CALC_RULE,
    PTRBDCA_WEEK1_IND,
    PTRBDCA_WEEK2_IND,
    PTRBDCA_WEEK3_IND,
    PTRBDCA_WEEK4_IND,
    PTRBDCA_WEEK5_IND,
    PTRBDCA_AMT1_IND,
    PTRBDCA_AMT2_IND,
    PTRBDCA_AMT3_IND,
    PTRBDCA_AMT4_IND,
    PTRBDCA_AMT1_TITLE,
    PTRBDCA_AMT2_TITLE,
    PTRBDCA_AMT3_TITLE,
    PTRBDCA_AMT4_TITLE,
    PTRBDCA_OPTION1_IND,
    PTRBDCA_OPTION2_IND,
    PTRBDCA_OPTION3_IND,
    PTRBDCA_OPTION4_IND,
    PTRBDCA_OPTION5_IND,
    PTRBDCA_OPTION1_TITLE,
    PTRBDCA_OPTION2_TITLE,
    PTRBDCA_OPTION3_TITLE,
    PTRBDCA_OPTION4_TITLE,
    PTRBDCA_OPTION5_TITLE,
    PTRBDCA_GROSS_REPORT_IND,
    PTRBDCA_BENEFIT_IND,
    PTRBDCA_TXCD_CODE,
    PTRBDCA_TAX_TYPE_IND,
    PTRBDCA_OVERLOAD_IND,
    PTRBDCA_ARREAR_IND,
    PTRBDCA_ACTIVITY_DATE,
    PTRBDCA_BDTY_CODE,
    PTRBDCA_AMT1_DESC,
    PTRBDCA_AMT2_DESC,
    PTRBDCA_AMT3_DESC,
    PTRBDCA_AMT4_DESC,
    PTRBDCA_1099_CODE,
    PTRBDCA_FLAT_AMT_IND,
    PTRBDCA_YTD_START_MONTH,
    PTRBDCA_WEB_DESC,
    PTRBDCA_WEB_INFO_URL,
    PTRBDCA_OPTION1_WEB_DESC,
    PTRBDCA_OPTION2_WEB_DESC,
    PTRBDCA_OPTION3_WEB_DESC,
    PTRBDCA_OPTION4_WEB_DESC,
    PTRBDCA_OPTION5_WEB_DESC,
    PTRBDCA_AMT1_WEB_DESC,
    PTRBDCA_AMT2_WEB_DESC,
    PTRBDCA_AMT3_WEB_DESC,
    PTRBDCA_AMT4_WEB_DESC,
    PTRBDCA_BDCL_CODE,
    PTRBDCA_COVERAGE_IND,
    PTRBDCA_BENEFICIARY_IND,
    --PTRBDCA_SURROGATE_ID,
    --PTRBDCA_VERSION,
    PTRBDCA_USER_ID,
    PTRBDCA_DATA_ORIGIN,
    --PTRBDCA_VPDI_CODE,
    PTRBDCA_DISP_WEB_PAYSTUB_IND,
    PTRBDCA_APPLGROSS_WPAYSTB_IND,
    PTRBDCA_ACA_HEALTH_PROVIDR_IND,
    PTRBDCA_ACA_OFFER_COVERAGE_CDE,
    PTRBDCA_ACA_4980H_SAFE_HBR_CDE,
    PTRBDCA_ACA_MLY_PREM_SELF_AMT,
    --PTRBDCA_GUID,
    PTRBDCA_AMT5_IND,
    PTRBDCA_AMT6_IND,
    PTRBDCA_AMT7_IND,
    PTRBDCA_AMT8_IND,
    PTRBDCA_AMT5_TITLE,
    PTRBDCA_AMT6_TITLE,
    PTRBDCA_AMT7_TITLE,
    PTRBDCA_AMT8_TITLE,
    PTRBDCA_AMT5_DESC,
    PTRBDCA_AMT6_DESC,
    PTRBDCA_AMT7_DESC,
    PTRBDCA_AMT8_DESC,
    PTRBDCA_AMT5_WEB_DESC,
    PTRBDCA_AMT6_WEB_DESC,
    PTRBDCA_AMT7_WEB_DESC,
    PTRBDCA_AMT8_WEB_DESC,
    PTRBDCA_PERS_PLAN_SIP_DESC,
    PTRBDCA_PERS_PLAN_SIP_ID,
    PTRBDCA_PERS_PROGRAM_TYPE,
    PTRBDCA_PERS_RECORD_TYPE
  )
  ( SELECT
      P_NEW_BDCA PTRBDCA_CODE,
      COALESCE(P_NEW_SHORT_DESC,PTRBDCA_SHORT_DESC) PTRBDCA_SHORT_DESC,
      COALESCE(P_NEW_LONG_DESC,PTRBDCA_LONG_DESC) PTRBDCA_LONG_DESC,
      PTRBDCA_PRIORITY,
      PTRBDCA_CALC_RULE,
      PTRBDCA_WEEK1_IND,
      PTRBDCA_WEEK2_IND,
      PTRBDCA_WEEK3_IND,
      PTRBDCA_WEEK4_IND,
      PTRBDCA_WEEK5_IND,
      PTRBDCA_AMT1_IND,
      PTRBDCA_AMT2_IND,
      PTRBDCA_AMT3_IND,
      PTRBDCA_AMT4_IND,
      PTRBDCA_AMT1_TITLE,
      PTRBDCA_AMT2_TITLE,
      PTRBDCA_AMT3_TITLE,
      PTRBDCA_AMT4_TITLE,
      PTRBDCA_OPTION1_IND,
      PTRBDCA_OPTION2_IND,
      PTRBDCA_OPTION3_IND,
      PTRBDCA_OPTION4_IND,
      PTRBDCA_OPTION5_IND,
      PTRBDCA_OPTION1_TITLE,
      PTRBDCA_OPTION2_TITLE,
      PTRBDCA_OPTION3_TITLE,
      PTRBDCA_OPTION4_TITLE,
      PTRBDCA_OPTION5_TITLE,
      PTRBDCA_GROSS_REPORT_IND,
      PTRBDCA_BENEFIT_IND,
      PTRBDCA_TXCD_CODE,
      PTRBDCA_TAX_TYPE_IND,
      PTRBDCA_OVERLOAD_IND,
      PTRBDCA_ARREAR_IND,
      SYSDATE PTRBDCA_ACTIVITY_DATE,
      PTRBDCA_BDTY_CODE,
      PTRBDCA_AMT1_DESC,
      PTRBDCA_AMT2_DESC,
      PTRBDCA_AMT3_DESC,
      PTRBDCA_AMT4_DESC,
      PTRBDCA_1099_CODE,
      PTRBDCA_FLAT_AMT_IND,
      PTRBDCA_YTD_START_MONTH,
      PTRBDCA_WEB_DESC,
      PTRBDCA_WEB_INFO_URL,
      PTRBDCA_OPTION1_WEB_DESC,
      PTRBDCA_OPTION2_WEB_DESC,
      PTRBDCA_OPTION3_WEB_DESC,
      PTRBDCA_OPTION4_WEB_DESC,
      PTRBDCA_OPTION5_WEB_DESC,
      PTRBDCA_AMT1_WEB_DESC,
      PTRBDCA_AMT2_WEB_DESC,
      PTRBDCA_AMT3_WEB_DESC,
      PTRBDCA_AMT4_WEB_DESC,
      PTRBDCA_BDCL_CODE,
      PTRBDCA_COVERAGE_IND,
      PTRBDCA_BENEFICIARY_IND,
      --PTRBDCA_SURROGATE_ID,
      --PTRBDCA_VERSION,
      USER PTRBDCA_USER_ID,
      LV_DATA_ORIGIN PTRBDCA_DATA_ORIGIN,
      --PTRBDCA_VPDI_CODE,
      PTRBDCA_DISP_WEB_PAYSTUB_IND,
      PTRBDCA_APPLGROSS_WPAYSTB_IND,
      PTRBDCA_ACA_HEALTH_PROVIDR_IND,
      PTRBDCA_ACA_OFFER_COVERAGE_CDE,
      PTRBDCA_ACA_4980H_SAFE_HBR_CDE,
      PTRBDCA_ACA_MLY_PREM_SELF_AMT,
      --PTRBDCA_GUID,
      PTRBDCA_AMT5_IND,
      PTRBDCA_AMT6_IND,
      PTRBDCA_AMT7_IND,
      PTRBDCA_AMT8_IND,
      PTRBDCA_AMT5_TITLE,
      PTRBDCA_AMT6_TITLE,
      PTRBDCA_AMT7_TITLE,
      PTRBDCA_AMT8_TITLE,
      PTRBDCA_AMT5_DESC,
      PTRBDCA_AMT6_DESC,
      PTRBDCA_AMT7_DESC,
      PTRBDCA_AMT8_DESC,
      PTRBDCA_AMT5_WEB_DESC,
      PTRBDCA_AMT6_WEB_DESC,
      PTRBDCA_AMT7_WEB_DESC,
      PTRBDCA_AMT8_WEB_DESC,
      PTRBDCA_PERS_PLAN_SIP_DESC,
      PTRBDCA_PERS_PLAN_SIP_ID,
      PTRBDCA_PERS_PROGRAM_TYPE,
      PTRBDCA_PERS_RECORD_TYPE
    FROM PTRBDCA@ZPPRD
    WHERE PTRBDCA_CODE = P_OLD_BDCA
      AND P_NEW_BDCA NOT IN (SELECT PTRBDCA_CODE FROM PTRBDCA) -- 20230821 TODO: TEST
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDCA' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'MAIN DEDUCTION SETUP');

  -- PTRBDPL - PLANS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDPL WHERE PTRBDPL_BDCA_CODE = P_NEW_BDCA 
      AND PTRBDPL_BDCA_CODE = P_OLD_BDCA
      AND PTRBDPL_EFFECTIVE_DATE = 
        ( SELECT MAX(JR.PTRBDPL_EFFECTIVE_DATE)
          FROM PTRBDPL@ZPPRD JR
          WHERE JR.PTRBDPL_BDCA_CODE = PTRBDPL.PTRBDPL_BDCA_CODE
        );
  INSERT INTO PTRBDPL (PTRBDPL_BDCA_CODE,
    PTRBDPL_CODE,
    PTRBDPL_DESC,
    PTRBDPL_AMT1,
    PTRBDPL_AMT2,
    PTRBDPL_AMT3,
    PTRBDPL_AMT4,
    PTRBDPL_ACTIVITY_DATE,
    PTRBDPL_EFFECTIVE_DATE,
    PTRBDPL_COVERAGE_IND,
    PTRBDPL_BENEFICIARY_IND,
    --PTRBDPL_SURROGATE_ID,
    --PTRBDPL_VERSION,
    PTRBDPL_USER_ID,
    PTRBDPL_DATA_ORIGIN
    --PTRBDPL_VPDI_CODE,
  )
  ( SELECT 
      P_NEW_BDCA PTRBDPL_BDCA_CODE,
      PTRBDPL_CODE,
      PTRBDPL_DESC,
      PTRBDPL_AMT1,
      PTRBDPL_AMT2,
      PTRBDPL_AMT3,
      PTRBDPL_AMT4,
      SYSDATE PTRBDPL_ACTIVITY_DATE,
      P_BEG_DATE PTRBDPL_EFFECTIVE_DATE,
      PTRBDPL_COVERAGE_IND,
      PTRBDPL_BENEFICIARY_IND,
      --PTRBDPL_SURROGATE_ID,
      --PTRBDPL_VERSION,
      USER PTRBDPL_USER_ID,
      LV_DATA_ORIGIN PTRBDPL_DATA_ORIGIN
      --PTRBDPL_VPDI_CODE
    FROM PTRBDPL@ZPPRD
    WHERE PTRBDPL_BDCA_CODE = P_OLD_BDCA
      AND PTRBDPL_EFFECTIVE_DATE = 
        ( SELECT MAX(JR.PTRBDPL_EFFECTIVE_DATE)
          FROM PTRBDPL@ZPPRD JR
          WHERE JR.PTRBDPL_BDCA_CODE = PTRBDPL.PTRBDPL_BDCA_CODE
        )
      AND (P_NEW_BDCA, PTRBDPL_CODE) NOT IN (SELECT PTRBDPL_BDCA_CODE, PTRBDPL_CODE FROM PTRBDPL) -- 20230821 TODO: TEST
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDPL' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'PLAN SETUP');

  -- PTRBDPD - PRECLUDED DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDPD WHERE PTRBDPD_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDPD (PTRBDPD_CODE,
    PTRBDPD_BDCA_CODE,
    PTRBDPD_ACTIVITY_DATE,
    --PTRBDPD_SURROGATE_ID,
    --PTRBDPD_VERSION,
    PTRBDPD_USER_ID,
    PTRBDPD_DATA_ORIGIN
    --PTRBDPD_VPDI_CODE
  )
  ( SELECT 
      P_NEW_BDCA PTRBDPD_CODE,
      PTRBDPD_BDCA_CODE,
      SYSDATE PTRBDPD_ACTIVITY_DATE,
      --PTRBDPD_SURROGATE_ID,
      --PTRBDPD_VERSION,
      USER PTRBDPD_USER_ID,
      LV_DATA_ORIGIN PTRBDPD_DATA_ORIGIN
      --PTRBDPD_VPDI_CODE
    FROM PTRBDPD@ZPPRD
    WHERE PTRBDPD_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDPD_BDCA_CODE) NOT IN (SELECT PTRBDPD_CODE, PTRBDPD_BDCA_CODE FROM PTRBDPD) -- 20230821 TODO: TEST
      AND PTRBDPD_BDCA_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDPD' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'PRECLUDED DEDUCTIONS SETUP');

  -- PTRBDAS - ASSOCIATED DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDAS WHERE PTRBDAS_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDAS (PTRBDAS_CODE,
    PTRBDAS_BDCA_CODE,
    PTRBDAS_ACTIVITY_DATE,
    --PTRBDAS_SURROGATE_ID,
    --PTRBDAS_VERSION,
    PTRBDAS_USER_ID,
    PTRBDAS_DATA_ORIGIN
    --PTRBDAS_VPDI_CODE,
  )
  ( SELECT 
      P_NEW_BDCA PTRBDAS_CODE,
      PTRBDAS_BDCA_CODE,
      SYSDATE PTRBDAS_ACTIVITY_DATE,
      --PTRBDAS_SURROGATE_ID,
      --PTRBDAS_VERSION,
      USER PTRBDAS_USER_ID,
      LV_DATA_ORIGIN PTRBDAS_DATA_ORIGIN
      --PTRBDAS_VPDI_CODE,
    FROM PTRBDAS@ZPPRD
    WHERE PTRBDAS_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDAS_BDCA_CODE) NOT IN (SELECT PTRBDAS_CODE, PTRBDAS_BDCA_CODE FROM PTRBDAS)
      AND PTRBDAS_BDCA_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDAS' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'ASSOCIATED DEDUCTIONS SETUP');

  -- PTRBDLG - COMBINED LIMIT GROUP
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDLG WHERE PTRBDLG_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDLG (PTRBDLG_CODE,
    PTRBDLG_BDCA_CODE,
    PTRBDLG_ACTIVITY_DATE,
    PTRBDLG_USER_ID,
    PTRBDLG_DATA_ORIGIN
    --PTRBDLG_SURROGATE_ID,
    --PTRBDLG_VERSION,
    --PTRBDLG_VPDI_CODE,
  )
  ( SELECT 
      P_NEW_BDCA PTRBDLG_CODE,
      PTRBDLG_BDCA_CODE,
      SYSDATE PTRBDLG_ACTIVITY_DATE,
      USER PTRBDLG_USER_ID,
      LV_DATA_ORIGIN PTRBDLG_DATA_ORIGIN
      --PTRBDLG_SURROGATE_ID,
      --PTRBDLG_VERSION,
      --PTRBDLG_VPDI_CODE,
    FROM PTRBDLG@ZPPRD
    WHERE PTRBDLG_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDLG_BDCA_CODE) NOT IN (SELECT PTRBDLG_CODE, PTRBDLG_BDCA_CODE FROM PTRBDLG)
      AND PTRBDLG_BDCA_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDLG' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'COMBINED LIMIT GROUP SETUP');

  -- PTRBDCG CORE DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDCG WHERE PTRBDCG_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDCG (PTRBDCG_CODE,
    PTRBDCG_BDCA_CODE,
    PTRBDCG_ACTIVITY_DATE,
    PTRBDCG_USER_ID,
    PTRBDCG_DATA_ORIGIN
    --PTRBDCG_SURROGATE_ID,
    --PTRBDCG_VERSION,
    --PTRBDCG_VPDI_CODE,
  )
  ( SELECT 
      P_NEW_BDCA PTRBDCG_CODE,
      PTRBDCG_BDCA_CODE,
      SYSDATE PTRBDCG_ACTIVITY_DATE,
      USER PTRBDCG_USER_ID,
      LV_DATA_ORIGIN PTRBDCG_DATA_ORIGIN
      --PTRBDCG_SURROGATE_ID,
      --PTRBDCG_VERSION,
      --PTRBDCG_VPDI_CODE,
    FROM PTRBDCG@ZPPRD
    WHERE PTRBDCG_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDCG_BDCA_CODE) NOT IN (SELECT PTRBDCG_CODE, PTRBDCG_BDCA_CODE FROM PTRBDCG) -- 20230821 TODO: TEST
      AND PTRBDCG_BDCA_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDCG' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'CORE DEDUCTIONS SETUP');

  -- INCLUDED BENEFITS OR DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDID WHERE PTRBDID_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDID (PTRBDID_CODE,
    PTRBDID_BDCA_CODE,
    PTRBDID_TAX_METHOD_IND,
    PTRBDID_ACTIVITY_DATE,
    PTRBDID_EMPL_EMPR_IND,
    --PTRBDID_SURROGATE_ID,
    --PTRBDID_VERSION,
    PTRBDID_USER_ID,
    PTRBDID_DATA_ORIGIN
    --PTRBDID_VPDI_CODE,
  )
  ( SELECT
      P_NEW_BDCA PTRBDID_CODE,
      PTRBDID_BDCA_CODE,
      PTRBDID_TAX_METHOD_IND,
      SYSDATE PTRBDID_ACTIVITY_DATE,
      PTRBDID_EMPL_EMPR_IND,
      --PTRBDID_SURROGATE_ID,
      --PTRBDID_VERSION,
      USER PTRBDID_USER_ID,
      LV_DATA_ORIGIN PTRBDID_DATA_ORIGIN
      --PTRBDID_VPDI_CODE,
    FROM PTRBDID@ZPPRD
    WHERE PTRBDID_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDID_BDCA_CODE) NOT IN (SELECT PTRBDID_CODE, PTRBDID_BDCA_CODE FROM PTRBDID)
      AND PTRBDID_BDCA_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDID' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'INCLUDED DEDUCTIONS SETUP');

  -- EXCLUDED DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDXD WHERE PTRBDXD_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDXD (PTRBDXD_CODE,
    PTRBDXD_BDCA_CODE,
    PTRBDXD_ACTIVITY_DATE,
    --PTRBDXD_SURROGATE_ID,
    --PTRBDXD_VERSION,
    PTRBDXD_USER_ID,
    PTRBDXD_DATA_ORIGIN
    --PTRBDXD_VPDI_CODE,
  )
  ( SELECT
      P_NEW_BDCA PTRBDXD_CODE,
      PTRBDXD_BDCA_CODE,
      SYSDATE PTRBDXD_ACTIVITY_DATE,
      --PTRBDXD_SURROGATE_ID,
      --PTRBDXD_VERSION,
      USER PTRBDXD_USER_ID,
      LV_DATA_ORIGIN PTRBDXD_DATA_ORIGIN
      --PTRBDXD_VPDI_CODE,
    FROM PTRBDXD@ZPPRD
    WHERE PTRBDXD_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDXD_BDCA_CODE) NOT IN (SELECT PTRBDXD_CODE, PTRBDXD_BDCA_CODE FROM PTRBDXD) -- 20230821 TODO: TEST
      AND PTRBDXD_BDCA_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDXD' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'EXCLUDED DEDUCTIONS SETUP');

  -- EXCLUDED EARNINGS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDXE WHERE PTRBDXE_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDXE (PTRBDXE_CODE,
    PTRBDXE_EARN_CODE,
    PTRBDXE_ACTIVITY_DATE,
    --PTRBDXE_SURROGATE_ID,
    --PTRBDXE_VERSION,
    PTRBDXE_USER_ID,
    PTRBDXE_DATA_ORIGIN
    --PTRBDXE_VPDI_CODE,
  )
  ( SELECT
      P_NEW_BDCA PTRBDXE_CODE,
      PTRBDXE_EARN_CODE,
      SYSDATE PTRBDXE_ACTIVITY_DATE,
      --PTRBDXE_SURROGATE_ID,
      --PTRBDXE_VERSION,
      USER PTRBDXE_USER_ID,
      LV_DATA_ORIGIN PTRBDXE_DATA_ORIGIN
      --PTRBDXE_VPDI_CODE,
    FROM PTRBDXE@ZPPRD
    WHERE PTRBDXE_CODE = P_OLD_BDCA
      AND (P_NEW_BDCA, PTRBDXE_EARN_CODE) NOT IN (SELECT PTRBDXE_CODE, PTRBDXE_EARN_CODE FROM PTRBDXE) -- 20230821 TODO: TEST
      AND PTRBDXE_EARN_CODE IN (SELECT PTREARN_CODE FROM PTREARN)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDXE' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'EXCLUDED EARNINGS SETUP');

  -- LABOR DISTRIBUTION OVERRIDE
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDLD WHERE PTRBDLD_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDLD (PTRBDLD_CODE,
    PTRBDLD_ECLS_CODE,
    PTRBDLD_COAS_CODE,
    PTRBDLD_ACCI_CODE_EMP_LIB,
    PTRBDLD_FUND_CODE_EMP_LIB,
    PTRBDLD_ORGN_CODE_EMP_LIB,
    PTRBDLD_ACCT_CODE_EMP_LIB,
    PTRBDLD_PROG_CODE_EMP_LIB,
    PTRBDLD_ACTV_CODE_EMP_LIB,
    PTRBDLD_LOCN_CODE_EMP_LIB,
    PTRBDLD_ACCI_CODE_EMR_EXP,
    PTRBDLD_FUND_CODE_EMR_EXP,
    PTRBDLD_ORGN_CODE_EMR_EXP,
    PTRBDLD_ACCT_CODE_EMR_EXP,
    PTRBDLD_PROG_CODE_EMR_EXP,
    PTRBDLD_ACTV_CODE_EMR_EXP,
    PTRBDLD_LOCN_CODE_EMR_EXP,
    PTRBDLD_ACCI_CODE_EMR_LIB,
    PTRBDLD_FUND_CODE_EMR_LIB,
    PTRBDLD_ORGN_CODE_EMR_LIB,
    PTRBDLD_ACCT_CODE_EMR_LIB,
    PTRBDLD_PROG_CODE_EMR_LIB,
    PTRBDLD_ACTV_CODE_EMR_LIB,
    PTRBDLD_LOCN_CODE_EMR_LIB,
    PTRBDLD_EMP_LIB_EXTERNAL,
    PTRBDLD_EMR_EXP_EXTERNAL,
    PTRBDLD_EMR_LIB_EXTERNAL,
    PTRBDLD_ACTIVITY_DATE,
    --PTRBDLD_SURROGATE_ID,
    --PTRBDLD_VERSION,
    PTRBDLD_USER_ID,
    PTRBDLD_DATA_ORIGIN
    --PTRBDLD_VPDI_CODE,
  )
  ( SELECT
      P_NEW_BDCA PTRBDLD_CODE,
      PTRBDLD_ECLS_CODE,
      PTRBDLD_COAS_CODE,
      PTRBDLD_ACCI_CODE_EMP_LIB,
      PTRBDLD_FUND_CODE_EMP_LIB,
      PTRBDLD_ORGN_CODE_EMP_LIB,
      PTRBDLD_ACCT_CODE_EMP_LIB,
      PTRBDLD_PROG_CODE_EMP_LIB,
      PTRBDLD_ACTV_CODE_EMP_LIB,
      PTRBDLD_LOCN_CODE_EMP_LIB,
      PTRBDLD_ACCI_CODE_EMR_EXP,
      PTRBDLD_FUND_CODE_EMR_EXP,
      PTRBDLD_ORGN_CODE_EMR_EXP,
      PTRBDLD_ACCT_CODE_EMR_EXP,
      PTRBDLD_PROG_CODE_EMR_EXP,
      PTRBDLD_ACTV_CODE_EMR_EXP,
      PTRBDLD_LOCN_CODE_EMR_EXP,
      PTRBDLD_ACCI_CODE_EMR_LIB,
      PTRBDLD_FUND_CODE_EMR_LIB,
      PTRBDLD_ORGN_CODE_EMR_LIB,
      PTRBDLD_ACCT_CODE_EMR_LIB,
      PTRBDLD_PROG_CODE_EMR_LIB,
      PTRBDLD_ACTV_CODE_EMR_LIB,
      PTRBDLD_LOCN_CODE_EMR_LIB,
      PTRBDLD_EMP_LIB_EXTERNAL,
      PTRBDLD_EMR_EXP_EXTERNAL,
      PTRBDLD_EMR_LIB_EXTERNAL,
      SYSDATE PTRBDLD_ACTIVITY_DATE,
      --PTRBDLD_SURROGATE_ID,
      --PTRBDLD_VERSION,
      USER PTRBDLD_USER_ID,
      LV_DATA_ORIGIN PTRBDLD_DATA_ORIGIN
      --PTRBDLD_VPDI_CODE,
    FROM PTRBDLD@ZPPRD
    WHERE PTRBDLD_CODE = P_OLD_BDCA
      AND PTRBDLD_ECLS_CODE IN (SELECT PTRECLS_CODE FROM PTRECLS)
      AND (P_NEW_BDCA, PTRBDLD_ECLS_CODE) NOT IN (SELECT PTRBDLD_CODE, PTRBDLD_ECLS_CODE FROM PTRBDLD) -- 20230821 TODO: TEST
      --AND 1=2 --SDL
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDLD' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'LABOR DISTRIBUTION OVERRIDE SETUP');

  -- PTRBPRV - PROVIDER INFORMATION SETUP
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBPRV WHERE PTRBPRV_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBPRV (PTRBPRV_BDCA_CODE,
    PTRBPRV_EFFECTIVE_DATE,
    PTRBPRV_PROVIDER_PIDM,
    PTRBPRV_ACTIVITY_DATE,
    PTRBPRV_USER_ID,
    PTRBPRV_DATA_ORIGIN,
    PTRBPRV_GROUP_ID
    --PTRBPRV_SURROGATE_ID,
    --PTRBPRV_VERSION,
    --PTRBPRV_VPDI_CODE,
  )
  ( SELECT 
      P_NEW_BDCA PTRBPRV_BDCA_CODE,
      PTRBPRV_EFFECTIVE_DATE,
      PTRBPRV_PROVIDER_PIDM,
      SYSDATE PTRBPRV_ACTIVITY_DATE,
      USER PTRBPRV_USER_ID,
      LV_DATA_ORIGIN PTRBPRV_DATA_ORIGIN,
      PTRBPRV_GROUP_ID
      --PTRBPRV_SURROGATE_ID,
      --PTRBPRV_VERSION,
      --PTRBPRV_VPDI_CODE,
    FROM PTRBPRV@ZPPRD
    WHERE PTRBPRV_BDCA_CODE = P_OLD_BDCA
      AND PTRBPRV_EFFECTIVE_DATE = 
        ( SELECT MAX(JR.PTRBPRV_EFFECTIVE_DATE)
          FROM PTRBPRV@ZPPRD JR
          WHERE JR.PTRBPRV_BDCA_CODE = PTRBPRV.PTRBPRV_BDCA_CODE
        )
      AND (P_NEW_BDCA, PTRBPRV_EFFECTIVE_DATE) NOT IN (SELECT PTRBPRV_BDCA_CODE, PTRBPRV_EFFECTIVE_DATE FROM PTRBPRV) -- 20230821 TODO: TEST
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBPRV' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'PROVIDER INFORMATION SETUP');

  --  Eligible Benefit Categories, PTRBCAT:
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBCDN WHERE PTRBCDN_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBCDN (PTRBCDN_BCAT_CODE,
    PTRBCDN_BDCA_CODE,
    PTRBCDN_REQ_IND,
    PTRBCDN_SETUP_IND,
    PTRBCDN_ACTIVITY_DATE,
    PTRBCDN_SEQ_NO,
    PTRBCDN_AMOUNT1,
    PTRBCDN_AMOUNT2,
    PTRBCDN_AMOUNT3,
    PTRBCDN_AMOUNT4,
    PTRBCDN_OPT_CODE1,
    PTRBCDN_OPT_CODE2,
    PTRBCDN_OPT_CODE3,
    PTRBCDN_OPT_CODE4,
    PTRBCDN_OPT_CODE5,
    PTRBCDN_BEGIN_DATE_IND,
    PTRBCDN_DEDN_STATUS,
    PTRBCDN_BEGIN_DATE,
    PTRBCDN_END_DATE,
    PTRBCDN_COVERAGE_END_DATE_IND,
    PTRBCDN_DISP_ON_STMT_IND,
    PTRBCDN_ENRL_BEGIN_DATE_METHOD,
    PTRBCDN_WAIT_DAY_MONTH_IND,
    PTRBCDN_NEWHIRE_CUTOFF_DAY,
    PTRBCDN_NEWHIRE_WAITING_PERIOD,
    --PTRBCDN_SURROGATE_ID,
    --PTRBCDN_VERSION,
    PTRBCDN_USER_ID,
    PTRBCDN_DATA_ORIGIN,
    --PTRBCDN_VPDI_CODE,
    PTRBCDN_ACA_START_PLAN_MONTH
  )
  ( SELECT 
      PTRBCDN_BCAT_CODE,
      P_NEW_BDCA PTRBCDN_BDCA_CODE,
      PTRBCDN_REQ_IND,
      PTRBCDN_SETUP_IND,
      SYSDATE PTRBCDN_ACTIVITY_DATE,
      PTRBCDN_SEQ_NO,
      PTRBCDN_AMOUNT1,
      PTRBCDN_AMOUNT2,
      PTRBCDN_AMOUNT3,
      PTRBCDN_AMOUNT4,
      PTRBCDN_OPT_CODE1,
      PTRBCDN_OPT_CODE2,
      PTRBCDN_OPT_CODE3,
      PTRBCDN_OPT_CODE4,
      PTRBCDN_OPT_CODE5,
      PTRBCDN_BEGIN_DATE_IND,
      PTRBCDN_DEDN_STATUS,
      P_BEG_DATE PTRBCDN_BEGIN_DATE,
      PTRBCDN_END_DATE,
      PTRBCDN_COVERAGE_END_DATE_IND,
      PTRBCDN_DISP_ON_STMT_IND,
      PTRBCDN_ENRL_BEGIN_DATE_METHOD,
      PTRBCDN_WAIT_DAY_MONTH_IND,
      PTRBCDN_NEWHIRE_CUTOFF_DAY,
      PTRBCDN_NEWHIRE_WAITING_PERIOD,
      --PTRBCDN_SURROGATE_ID,
      --PTRBCDN_VERSION,
      USER PTRBCDN_USER_ID,
      LV_DATA_ORIGIN PTRBCDN_DATA_ORIGIN,
      --PTRBCDN_VPDI_CODE,
      PTRBCDN_ACA_START_PLAN_MONTH
    FROM PTRBCDN@ZPPRD
    WHERE PTRBCDN_BDCA_CODE = P_OLD_BDCA
      AND (PTRBCDN_BCAT_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBCDN_BCAT_CODE, PTRBCDN_BDCA_CODE FROM PTRBCDN) -- 20230821 TODO: TEST
      AND PTRBCDN_BCAT_CODE IN (SELECT PTRBCAT_CODE FROM PTRBCAT)
      AND COALESCE(PTRBCDN_END_DATE, P_BEG_DATE) >= P_BEG_DATE
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBCDN' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'SELF' || CHR(9) || 'BENEFIT CATEGORY DEDUCTIONS SETUP');

  --  Reciprocations with Other BDCA Codes:
  -- PTRBDPD - PRECLUDED DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDPD WHERE PTRBDPD_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDPD (PTRBDPD_CODE,
    PTRBDPD_BDCA_CODE,
    PTRBDPD_ACTIVITY_DATE,
    --PTRBDPD_SURROGATE_ID,
    --PTRBDPD_VERSION,
    PTRBDPD_USER_ID,
    PTRBDPD_DATA_ORIGIN
    --PTRBDPD_VPDI_CODE,
  )
  ( SELECT
      PTRBDPD_CODE,
      P_NEW_BDCA PTRBDPD_BDCA_CODE,
      SYSDATE PTRBDPD_ACTIVITY_DATE,
      --PTRBDPD_SURROGATE_ID,
      --PTRBDPD_VERSION,
      USER PTRBDPD_USER_ID,
      LV_DATA_ORIGIN PTRBDPD_DATA_ORIGIN
      --PTRBDPD_VPDI_CODE,
    FROM PTRBDPD@ZPPRD
    WHERE PTRBDPD_BDCA_CODE = P_OLD_BDCA
      AND (PTRBDPD_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBDPD_CODE, PTRBDPD_BDCA_CODE FROM PTRBDPD) -- 20230821 TODO: TEST
      AND PTRBDPD_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA) -- 20230821 TODO: TEST
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDPD' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'PRECLUDED DEDUCTIONS SETUP');

  -- PTRBDAS - ASSOCIATED DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDAS WHERE PTRBDAS_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDAS (PTRBDAS_CODE,
    PTRBDAS_BDCA_CODE,
    PTRBDAS_ACTIVITY_DATE,
    --PTRBDAS_SURROGATE_ID,
    --PTRBDAS_VERSION,
    PTRBDAS_USER_ID,
    PTRBDAS_DATA_ORIGIN
    --PTRBDAS_VPDI_CODE,
  )
  ( SELECT 
      PTRBDAS_CODE,
      P_NEW_BDCA PTRBDAS_BDCA_CODE,
      SYSDATE PTRBDAS_ACTIVITY_DATE,
      --PTRBDAS_SURROGATE_ID,
      --PTRBDAS_VERSION,
      USER PTRBDAS_USER_ID,
      LV_DATA_ORIGIN PTRBDAS_DATA_ORIGIN
      --PTRBDAS_VPDI_CODE,
    FROM PTRBDAS@ZPPRD
    WHERE PTRBDAS_BDCA_CODE = P_OLD_BDCA
      AND (PTRBDAS_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBDAS_CODE, PTRBDAS_BDCA_CODE FROM PTRBDAS)
      AND PTRBDAS_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDAS' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'ASSOCIATED DEDUCTIONS SETUP');

  -- PTRBDLG - COMBINED LIMIT GROUP
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDLG WHERE PTRBDLG_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDLG (PTRBDLG_CODE,
    PTRBDLG_BDCA_CODE,
    PTRBDLG_ACTIVITY_DATE,
    PTRBDLG_USER_ID,
    PTRBDLG_DATA_ORIGIN
    --PTRBDLG_SURROGATE_ID,
    --PTRBDLG_VERSION,
    --PTRBDLG_VPDI_CODE,
  )
  ( SELECT 
      PTRBDLG_CODE,
      P_NEW_BDCA PTRBDLG_BDCA_CODE,
      SYSDATE PTRBDLG_ACTIVITY_DATE,
      USER PTRBDLG_USER_ID,
      LV_DATA_ORIGIN PTRBDLG_DATA_ORIGIN
      --PTRBDLG_SURROGATE_ID,
      --PTRBDLG_VERSION,
      --PTRBDLG_VPDI_CODE,
    FROM PTRBDLG@ZPPRD
    WHERE PTRBDLG_BDCA_CODE = P_OLD_BDCA
      AND (PTRBDLG_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBDLG_CODE, PTRBDLG_BDCA_CODE FROM PTRBDLG)
      AND PTRBDLG_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDLG' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'COMBINED LIMIT GROUP SETUP');
  -- PTRBDCG CORE DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDCG WHERE PTRBDCG_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDCG (PTRBDCG_CODE,
    PTRBDCG_BDCA_CODE,
    PTRBDCG_ACTIVITY_DATE,
    PTRBDCG_USER_ID,
    PTRBDCG_DATA_ORIGIN
    --PTRBDCG_SURROGATE_ID,
    --PTRBDCG_VERSION,
    --PTRBDCG_VPDI_CODE,
  )
  ( SELECT 
      PTRBDCG_CODE,
      P_NEW_BDCA PTRBDCG_BDCA_CODE,
      SYSDATE PTRBDCG_ACTIVITY_DATE,
      USER PTRBDCG_USER_ID,
      LV_DATA_ORIGIN PTRBDCG_DATA_ORIGIN
      --PTRBDCG_SURROGATE_ID,
      --PTRBDCG_VERSION,
      --PTRBDCG_VPDI_CODE,
    FROM PTRBDCG@ZPPRD
    WHERE PTRBDCG_BDCA_CODE = P_OLD_BDCA
      AND (PTRBDCG_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBDCG_CODE, PTRBDCG_BDCA_CODE FROM PTRBDCG) -- 20230821 TODO: TEST
      AND PTRBDCG_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDCG' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'CORE DEDUCTIONS SETUP');

  -- INCLUDED BENEFITS OR DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDID WHERE PTRBDID_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDID (PTRBDID_CODE,
    PTRBDID_BDCA_CODE,
    PTRBDID_TAX_METHOD_IND,
    PTRBDID_ACTIVITY_DATE,
    PTRBDID_EMPL_EMPR_IND,
    --PTRBDID_SURROGATE_ID,
    --PTRBDID_VERSION,
    PTRBDID_USER_ID,
    PTRBDID_DATA_ORIGIN
    --PTRBDID_VPDI_CODE,
  )
  ( SELECT 
      PTRBDID_CODE,
      P_NEW_BDCA PTRBDID_BDCA_CODE,
      PTRBDID_TAX_METHOD_IND,
      SYSDATE PTRBDID_ACTIVITY_DATE,
      PTRBDID_EMPL_EMPR_IND,
      --PTRBDID_SURROGATE_ID,
      --PTRBDID_VERSION,
      USER PTRBDID_USER_ID,
      LV_DATA_ORIGIN PTRBDID_DATA_ORIGIN
      --PTRBDID_VPDI_CODE,
    FROM PTRBDID@ZPPRD
    WHERE PTRBDID_BDCA_CODE = P_OLD_BDCA
      AND (PTRBDID_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBDID_CODE, PTRBDID_BDCA_CODE FROM PTRBDID)
      AND PTRBDID_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDID' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'INCLUDED DEDUCTIONS SETUP');

  -- EXCLUDED DEDUCTIONS
  SELECT COUNT(*) INTO LV_REC_CNT FROM PTRBDXD WHERE PTRBDXD_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO PTRBDXD (PTRBDXD_CODE,
    PTRBDXD_BDCA_CODE,
    PTRBDXD_ACTIVITY_DATE,
    --PTRBDXD_SURROGATE_ID,
    --PTRBDXD_VERSION,
    PTRBDXD_USER_ID,
    PTRBDXD_DATA_ORIGIN
    --PTRBDXD_VPDI_CODE,
  )
  ( SELECT
      PTRBDXD_CODE,
      P_NEW_BDCA PTRBDXD_BDCA_CODE,
      SYSDATE PTRBDXD_ACTIVITY_DATE,
      --PTRBDXD_SURROGATE_ID,
      --PTRBDXD_VERSION,
      USER PTRBDXD_USER_ID,
      LV_DATA_ORIGIN PTRBDXD_DATA_ORIGIN
      --PTRBDXD_VPDI_CODE,
    FROM PTRBDXD@ZPPRD
    WHERE PTRBDXD_BDCA_CODE = P_OLD_BDCA
      AND (PTRBDXD_CODE, P_NEW_BDCA) NOT IN (SELECT PTRBDXD_CODE, PTRBDXD_BDCA_CODE FROM PTRBDXD)
      AND PTRBDXD_CODE IN (SELECT PTRBDCA_CODE FROM PTRBDCA)
  );

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'PTRBDXD' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'EXCLUDED DEDUCTIONS SETUP');

  -- ZHBBDCA - USU BREAKDOWN GROUP ASSIGNMENT FOR EMPLOYER EXPENSE (OR LIABILITY?)
  SELECT COUNT(*) INTO LV_REC_CNT FROM ZHBBDCA WHERE ZHBBDCA_BDCA_CODE = P_NEW_BDCA;
  INSERT INTO ZHBBDCA (ZHBBDCA_COAS_CODE, ZHBBDCA_BDCA_CODE, ZHBBDCA_BREAKDOWN_GROUP, ZHBBDCA_ACTIVITY_DATE, ZHBBDCA_USER_ID, ZHBBDCA_DATA_ORIGIN)
  ( SELECT ZHBBDCA_COAS_CODE
    , P_NEW_BDCA ZHBBDCA_BDCA_CODE
    , ZHBBDCA_BREAKDOWN_GROUP
    , SYSDATE ZHBBDCA_ACTIVITY_DATE
    , USER ZHBBDCA_USER_ID
    , LV_DATA_ORIGIN ZHBBDCA_DATA_ORIGIN
    FROM ZHBBDCA@ZPPRD
    WHERE ZHBBDCA_BDCA_CODE = P_OLD_BDCA
      AND (ZHBBDCA_COAS_CODE, P_NEW_BDCA, ZHBBDCA_BREAKDOWN_GROUP) NOT IN (SELECT ZHBBDCA_COAS_CODE, ZHBBDCA_BDCA_CODE, ZHBBDCA_BREAKDOWN_GROUP FROM ZHBBDCA) -- 20230821 TODO: TEST
      --AND 1=2 --SDL
  );
  
  -- SELECT COUNT(*) INTO LV_REC_CNT FROM ZHBBDCA WHERE ZHBBDCA_CODE = P_NEW_BDCA;
  -- INSERT INTO ZHBBDCA (ZHBBDCA_COAS_CODE, ZHBBDCA_BDCA_CODE, ZHBBDCA_BREAKDOWN_GROUP) VALUES ('R',P_NEW_BDCA,'3'); --SDL

  DBMS_OUTPUT.PUT_LINE(P_NEW_BDCA || CHR(9) || P_OLD_BDCA || CHR(9) || 'ZHBBDCA' || CHR(9) || LV_REC_CNT || CHR(9) || SQL%ROWCOUNT || CHR(9) || 'INSERTED' || CHR(9) || 'OTHR' || CHR(9) || 'USU FRINGE BREAKOUT GROUP');

END;
/
-- ROLLBACK;
-- COMMIT;

 -- View records
 SELECT * FROM PTRBDCA WHERE PTRBDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDPL WHERE PTRBDPL_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDPD WHERE PTRBDPD_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDAS WHERE PTRBDAS_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDCG WHERE PTRBDCG_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDID WHERE PTRBDID_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDXD WHERE PTRBDXD_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDXE WHERE PTRBDXE_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDLD WHERE PTRBDLD_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBCDN WHERE PTRBCDN_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDPD WHERE PTRBDPD_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDAS WHERE PTRBDAS_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDCG WHERE PTRBDCG_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDID WHERE PTRBDID_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM PTRBDXD WHERE PTRBDXD_BDCA_CODE = UPPER(:NEW_BDCA_CODE);
 SELECT * FROM POSNCTL.ZHBBDCA WHERE ZHBBDCA_BDCA_CODE = UPPER(:NEW_BDCA_CODE);